# Configuracion del servidor
server:
  port: 8080

# Configuracion de la base de datos
spring:
  datasource:
    url: jdbc:mysql://b8weeidsavcw9yhkez6v-mysql.services.clever-cloud.com:3306/b8weeidsavcw9yhkez6v
    username: ugwuypjentlyfjio
    password: 1ynbl241qyroHT0Xprz0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


# Configuracion de seguridad
security:
  user:
    name: admin
    password: 1234

#Configuracion Springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html



#Configuracion de Jwt
jwt:
  secret: "tuClaveSecretaDebeSerMuyLargaYSegura32"
  expiration: 3600000

# Configuracion de logger
logging:
  level:
    root: info
    org:
      springframework: debug
  file:
    name: logs/application.log